apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deny_all_authorizationpolicy.yaml
- gateway.yaml
- gateway_authorizationpolicy.yaml

bases:
- ../../../upstream/common/istio-1-14/istio-install/base

patchesStrategicMerge:
- patches/service.yaml