apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- secrets-manager.yaml
- secrets-mount.yaml
bases:
- ../../env/platform-agnostic
configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- disable-default-secrets.yaml
- aws-configuration-patch.yaml
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
