apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- updated-AMP-service-account.yaml
- clusterRole.yaml
- updated-config-map.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
