apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kubeflow namespace
  - ../../upstream/common/kubeflow-namespace/base
  # Kubeflow Roles
  - ../../upstream/common/kubeflow-roles/base
  # Cert-Manager
  - ../../upstream/common/cert-manager/cert-manager/base
  - ../../upstream/common/cert-manager/kubeflow-issuer/base
  # Istio
  - ../../upstream/common/istio-1-16/istio-crds/base
  - ../../upstream/common/istio-1-16/istio-namespace/base
  - ../../upstream/common/istio-1-16/istio-install/base
  # KNative
  - ../../upstream/common/knative/knative-serving/overlays/gateways
  - ../../upstream/common/knative/knative-eventing/base
  - ../../upstream/common/istio-1-16/cluster-local-gateway/base
  # Kubeflow Istio Resources
  - ../../upstream/common/istio-1-16/kubeflow-istio-resources/base

  # Central Dashboard
  - ../../awsconfigs/apps/centraldashboard
  # Notebooks
  - ../../awsconfigs/apps/jupyter-web-app
  - ../../awsconfigs/apps/notebook-controller
  # Admission Webhook
  - ../../upstream/apps/admission-webhook/upstream/overlays/cert-manager
  # Profiles + KFAM
  - ../../upstream/apps/profiles/upstream/overlays/kubeflow
  # Volumes Web App
  - ../../upstream/apps/volumes-web-app/upstream/overlays/istio
  # Tensorboard
  - ../../upstream/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  - ../../upstream/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
  # Training Operator
  - ../../upstream/apps/training-operator/upstream/overlays/kubeflow
  # AWS Telemetry - This is an optional component. See usage tracking documentation for more information
  - ../../awsconfigs/common/aws-telemetry

  # KServe
  - ../../awsconfigs/apps/kserve
  - ../../upstream/contrib/kserve/models-web-app/overlays/kubeflow

  # ACK Sagemaker
  - ../../awsconfigs/common/ack-sagemaker-controller
  
  # Configured for AWS Cognito

  # Ingress
  - ../../awsconfigs/common/istio-ingress/overlays/cognito
  # ALB controller
  - ../../awsconfigs/common/aws-alb-ingress-controller/base
  # Authservice
  - ../../awsconfigs/common/aws-authservice/base

  # Configured for AWS RDS and AWS S3

  # AWS Secret Manager
  - ../../awsconfigs/common/aws-secrets-manager
  # Kubeflow Pipelines
  - ../../awsconfigs/apps/pipeline
  # Katib
  - ../../awsconfigs/apps/katib-external-db-with-kubeflow
