name: hugo-build-push-folder

on:
  # Trigger the workflow on git push to a branch where this workflow file exists 
  push:
    branches:
      - main
      - 'release-v[0-9].[0-9]+.[0-9]+-aws-b[0-9].[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive 
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.93.0'
          extended: true

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE/website
          npm install postcss-cli@8.3.0
          base_url="baseURL = \"https://$GITHUB_REPOSITORY_OWNER.github.io/kubeflow-manifests/$(git branch --show-current)\""
          sed -i "1s#.*#$base_url#" config.toml
          hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
          keep_files: true          
